### ISSUE TITLE
有趣的动画，谢谢分享，反馈几个问题

### ISSUE THREAD

**Issue by 03128crz** [AYJk/AYPageControl#1]
1 直接设置圆圈直径不生效。
    self.pageControlView.ballDiameter = 5;
只能在代码中直接修改

```
@implementation AYLineLayer

- (instancetype)init {

    if (self = [super init]) {
        self.numberOfPages = 3;
        self.currentPage = 1;
        self.ballDiameter = 5.0;
        self.unSelectedColor = [UIColor lightGrayColor];
        self.selectedColor = [UIColor clearColor];
    }
    return self;
}
```

2.设置圆圈直径后对焦点圆圈不生效
![snip20160519_1](https://cloud.githubusercontent.com/assets/3424553/15380233/56f6ab0a-1da7-11e6-88a5-31c3b8c02954.png)

3.能否提供设置圆圈之间距离的方法

**Comment by AYJk** [comment]
开始忙新项目了，我会尽快解决相关问题的，谢谢反馈。
